% params = struct(...
    % 'file', 'output/data_N.mat',...
    % 'maxEpochs', 10000,...
    % 'path', 'output29/',...
    % 'rollback', false,...
    % 'eta', 0.25,...
    % 'etaEps', 0.001,...
    % 'etaInc', 0.01,...
    % 'etaDec', 0.001,...
    % 'etaSteps', 3,...
    % 'momentum', 0.5,...
    % 'inputSamples', 100,...
    % 'inputDim', 2,...
    % 'beta', 1,...
    % 'pps', 20);

% params = struct(...
%     % 'path', 'output8/',...
%     % 'inputSamples', 10,...
%     'rollback', true,...
%     % 'etaEps', 0.02,...
%     % 'etaDec', 0.001,...
%     % 'etaInc', 0.1,...
%     'maxEpochs', 199);

params = struct('maxEpochs', 199);

i = 9;

for etaEps = [0.0001, 0.001, 0.01, 0.1]

    for etaInc = [0.001, 0.01, 0.1]

        for etaDec = [0.0001, 0.001, 0.01, 0.1]

            for etaSteps = [2, 3, 4]

                fprintf('eps: '); disp(etaEps);
                fprintf('inc: '); disp(etaInc);
                fprintf('dec: '); disp(etaDec);
                fprintf('steps: '); disp(etaSteps);

                params.etaEps = etaEps;
                params.etaInc = etaInc;
                params.etaDec = etaDec;
                params.etaSteps = etaSteps;

                i = i + 1;

                fprintf('i: '); disp(i);

                params.path = strcat('output', int2str(i), '/');

                algorithm.main([4 4], params);
            end
        end
    end
end

