% params = struct(...
    % 'file', 'output/data_N.mat',...
    % 'maxEpochs', 10000,...
    % 'path', 'output29/',...
    % 'rollback', false,...
    % 'eta', 0.25,...
    % 'etaEps', 0.001,...
    % 'etaInc', 0.01,...
    % 'etaDec', 0.001,...
    % 'etaSteps', 3,...
    % 'momentum', 0.5,...
    % 'inputSamples', 100,...
    % 'inputDim', 2,...
    % 'beta', 1,...
    % 'pps', 20);

% params = struct(...
%     % 'path', 'output8/',...
%     % 'inputSamples', 10,...
%     'rollback', true,...
%     % 'etaEps', 0.02,...
%     % 'etaDec', 0.001,...
%     % 'etaInc', 0.1,...
%     'maxEpochs', 199);

params = struct('maxEpochs', 199);

params.path = 'output11/'; algorithm.main([4 4], params);
params.path = 'output12/'; algorithm.main([4 4], params);
params.path = 'output13/'; algorithm.main([4 4], params);

params.g = @functions.sigmoidTanh;
params.dg = @functions.DsigmoidTanh;

params.path = 'output21/'; algorithm.main([4 4], params);
params.path = 'output22/'; algorithm.main([4 4], params);
params.path = 'output23/'; algorithm.main([4 4], params);

