% params = struct(...
    % 'file', 'output/data_N.mat',...
    % 'maxEpochs', 10000,...
    % 'path', 'output29/',...
    % 'rollback', false,...
    % 'eta', 0.25,...
    % 'etaEps', 0.001,...
    % 'etaInc', 0.01,...
    % 'etaDec', 0.001,...
    % 'etaSteps', 3,...
    % 'momentum', 0.5,...
    % 'inputSamples', 100,...
    % 'inputDim', 2,...
    % 'beta', 1,...
    % 'pps', 20);

% params = struct(...
%     'path', 'output8/',...
%     'inputSamples', 10,...
%     'rollback', true,...
%     'etaEps', 0.02,...
%     'etaDec', 0.001,...
%     'etaInc', 0.1,...
%     'maxEpochs', 199);

params = struct('maxEpochs', 199);

params.path = 'output101/'; algorithm.main([9 6], params);
params.path = 'output102/'; algorithm.main([9 6], params);
params.path = 'output103/'; algorithm.main([9 6], params);

params.path = 'output111/'; algorithm.main([9 9], params);
params.path = 'output112/'; algorithm.main([9 9], params);
params.path = 'output113/'; algorithm.main([9 9], params);

params.path = 'output121/'; algorithm.main([3 5], params);
params.path = 'output122/'; algorithm.main([3 5], params);
params.path = 'output123/'; algorithm.main([3 5], params);

